# docker-compose.yml - Define CÓMO los contenedores trabajan juntos
version: '3'

services:
  # Servicio 1: Nuestra aplicación web
  web:
    build: .                    # Usa el Dockerfile local
    ports:
      - "5000:5000"            # Mapeo de puertos
    environment:
      - REDIS_HOST=redis       # Variable de entorno
    depends_on:
      - redis                  # Dependencia
    networks:
      - app-network            # Red compartida

  # Servicio 2: Redis
  redis:
    image: redis:alpine        # Usa imagen directa de Docker Hub
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data       # Persistencia de datos
    networks:
      - app-network

networks:
  app-network:                 # Define la red que comparten

volumes:
  redis_data:                  # Define el volumen para persistencia