version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - dev-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - dev-network
    volumes:
      - redis-data:/data

networks:
  dev-network:

volumes:
  redis-data: